quarkus:
  resteasy:
    path: /api
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/xsender_db
    username: xsender_username
    password: xsender_password
  hibernate-orm:
    database:
      generation: update
  quartz:
    clustered: false
  artemis:
    url: tcp://localhost:61616
    username: quarkus
    password: quarkus
    health:
      enabled: false
  oidc:
    enabled: true
    auth-server-url: http://localhost:8180/auth/realms/openubl
    client-id: xsender
    credentials:
      secret: secret
  http:
    auth:
      permission:
        hmtl:
          paths: /*
          policy: permit
        api:
          paths: /api/*
          policy: authenticated

kafka:
  bootstrap:
    servers: localhost:9092


mp:
  messaging:
    connector:
      smallrye-kafka:
        apicurio:
          registry:
            url: http://localhost:8081/api
    outgoing:
      entity-event:
        connector: smallrye-kafka
        topic: entity-event
        value:
          serializer: io.apicurio.registry.utils.serde.AvroKafkaSerializer
        apicurio:
          registry:
            artifact-id: io.apicurio.registry.utils.serde.strategy.SimpleTopicIdStrategy
            global-id: io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy
            avro-datum-provider: io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider
    incoming:
      entity-event-from-kafka:
        connector: smallrye-kafka
        topic: entity-event
        value:
          deserializer: io.apicurio.registry.utils.serde.AvroKafkaDeserializer
        auto:
          offset:
            reset: earliest
        enable:
          auto:
            commit: false
        apicurio:
          registry:
            avro-datum-provider: io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider

openubl:
  event-manager:
    type: basic
    basic:
      retry-delay: 43200000
    jms:
      delay: 500
      callbackQueue: callbackQueue
      sendFileQueue: sendFileQueue
      ticketQueue: ticketQueue
  storage:
    type: filesystem
    filesystem:
      folder: target/xsender-server-storage
    s3:
      host: http://localhost:9000
      region: us-east-1
      bucket: project-openubl
      access_key_id: BQA2GEXO711FVBVXDWKM
      secret_access_key: uvgz3LCwWM3e400cDkQIH/y1Y4xgU4iV91CwFSPC
