quarkus:
  resteasy:
    path: /api

  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/xsender_db
    username: xsender_username
    password: xsender_password

  hibernate-orm:
    database:
      generation: none
    sql-load-script: no-file
    log:
      sql: false

  flyway:
    migrate-at-start: true
    connect-retries: 3

  oidc:
    enabled: true
    auth-server-url: http://localhost:8180/auth/realms/openubl
    client-id: xsender
    credentials:
      secret: secret
  http:
    auth:
      permission:
        hmtl:
          paths: /*
          policy: permit
        api:
          paths: /api/*
          policy: authenticated
  kafka:
    health:
      enabled: true

kafka:
  bootstrap:
    servers: localhost:9092

mp:
  messaging:
    connector:
      smallrye-kafka:
        apicurio:
          registry:
            url: http://localhost:8280/api
    outgoing:
      company-event:
        connector: smallrye-kafka
        topic: company-event
        value:
          serializer: io.apicurio.registry.utils.serde.AvroKafkaSerializer
        apicurio:
          registry:
            artifact-id: io.apicurio.registry.utils.serde.strategy.SimpleTopicIdStrategy
            global-id: io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy
            avro-datum-provider: io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider
      document-event:
        connector: smallrye-kafka
        topic: document-event
        value:
          serializer: io.apicurio.registry.utils.serde.AvroKafkaSerializer
        apicurio:
          registry:
            artifact-id: io.apicurio.registry.utils.serde.strategy.SimpleTopicIdStrategy
            global-id: io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy
            avro-datum-provider: io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider
      read-documents:
        connector: smallrye-kafka
        topic: read-documents
        value:
          serializer: io.apicurio.registry.utils.serde.AvroKafkaSerializer
        apicurio:
          registry:
            artifact-id: io.apicurio.registry.utils.serde.strategy.SimpleTopicIdStrategy
            global-id: io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy
            avro-datum-provider: io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider
      send-documents:
        connector: smallrye-kafka
        topic: send-documents
        value:
          serializer: io.apicurio.registry.utils.serde.AvroKafkaSerializer
        apicurio:
          registry:
            artifact-id: io.apicurio.registry.utils.serde.strategy.SimpleTopicIdStrategy
            global-id: io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy
            avro-datum-provider: io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider
      send-documents1:
        connector: smallrye-kafka
        topic: send-documents1
        value:
          serializer: io.apicurio.registry.utils.serde.AvroKafkaSerializer
        apicurio:
          registry:
            artifact-id: io.apicurio.registry.utils.serde.strategy.SimpleTopicIdStrategy
            global-id: io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy
            avro-datum-provider: io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider
      send-documents2:
        connector: smallrye-kafka
        topic: send-documents2
        value:
          serializer: io.apicurio.registry.utils.serde.AvroKafkaSerializer
        apicurio:
          registry:
            artifact-id: io.apicurio.registry.utils.serde.strategy.SimpleTopicIdStrategy
            global-id: io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy
            avro-datum-provider: io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider
      send-documents3:
        connector: smallrye-kafka
        topic: send-documents3
        value:
          serializer: io.apicurio.registry.utils.serde.AvroKafkaSerializer
        apicurio:
          registry:
            artifact-id: io.apicurio.registry.utils.serde.strategy.SimpleTopicIdStrategy
            global-id: io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy
            avro-datum-provider: io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider
      check-ticket:
        connector: smallrye-kafka
        topic: check-ticket
        value:
          serializer: io.apicurio.registry.utils.serde.AvroKafkaSerializer
        apicurio:
          registry:
            artifact-id: io.apicurio.registry.utils.serde.strategy.SimpleTopicIdStrategy
            global-id: io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy
            avro-datum-provider: io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider
      error-ticket:
        connector: smallrye-kafka
        topic: error-ticket
        value:
          serializer: io.apicurio.registry.utils.serde.AvroKafkaSerializer
        apicurio:
          registry:
            artifact-id: io.apicurio.registry.utils.serde.strategy.SimpleTopicIdStrategy
            global-id: io.apicurio.registry.utils.serde.strategy.GetOrCreateIdStrategy
            avro-datum-provider: io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider
    incoming:
      incoming-company-event:
        connector: smallrye-kafka
        topic: company-event
        value:
          deserializer: io.apicurio.registry.utils.serde.AvroKafkaDeserializer
        auto:
          offset:
            reset: earliest
        enable:
          auto:
            commit: false
        apicurio:
          registry:
            avro-datum-provider: io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider
      incoming-document-event:
        connector: smallrye-kafka
        topic: document-event
        value:
          deserializer: io.apicurio.registry.utils.serde.AvroKafkaDeserializer
        auto:
          offset:
            reset: earliest
        enable:
          auto:
            commit: false
        apicurio:
          registry:
            avro-datum-provider: io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider
      incoming-read-documents:
        connector: smallrye-kafka
        topic: read-documents
        value:
          deserializer: io.apicurio.registry.utils.serde.AvroKafkaDeserializer
        auto:
          offset:
            reset: earliest
        enable:
          auto:
            commit: false
        apicurio:
          registry:
            avro-datum-provider: io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider
      incoming-send-documents:
        connector: smallrye-kafka
        topic: send-documents
        value:
          deserializer: io.apicurio.registry.utils.serde.AvroKafkaDeserializer
        auto:
          offset:
            reset: earliest
        enable:
          auto:
            commit: false
        apicurio:
          registry:
            avro-datum-provider: io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider
      incoming-send-documents1:
        connector: smallrye-kafka
        topic: send-documents1
        value:
          deserializer: io.apicurio.registry.utils.serde.AvroKafkaDeserializer
        auto:
          offset:
            reset: earliest
        enable:
          auto:
            commit: false
        apicurio:
          registry:
            avro-datum-provider: io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider
      incoming-send-documents2:
        connector: smallrye-kafka
        topic: send-documents2
        value:
          deserializer: io.apicurio.registry.utils.serde.AvroKafkaDeserializer
        auto:
          offset:
            reset: earliest
        enable:
          auto:
            commit: false
        apicurio:
          registry:
            avro-datum-provider: io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider
      incoming-send-documents3:
        connector: smallrye-kafka
        topic: send-documents3
        value:
          deserializer: io.apicurio.registry.utils.serde.AvroKafkaDeserializer
        auto:
          offset:
            reset: earliest
        enable:
          auto:
            commit: false
        apicurio:
          registry:
            avro-datum-provider: io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider
      incoming-check-ticket:
        connector: smallrye-kafka
        topic: check-ticket
        value:
          deserializer: io.apicurio.registry.utils.serde.AvroKafkaDeserializer
        auto:
          offset:
            reset: earliest
        enable:
          auto:
            commit: false
        apicurio:
          registry:
            avro-datum-provider: io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider
      incoming-error-ticket:
        connector: smallrye-kafka
        topic: error-ticket
        value:
          deserializer: io.apicurio.registry.utils.serde.AvroKafkaDeserializer
        auto:
          offset:
            reset: earliest
        enable:
          auto:
            commit: false
        apicurio:
          registry:
            avro-datum-provider: io.apicurio.registry.utils.serde.avro.ReflectAvroDatumProvider

openubl:
  storage:
    type: filesystem
    filesystem:
      folder: target/xsender-server-storage
    s3:
      host: http://localhost:9000
      region: us-east-1
      bucket: project-openubl
      access_key_id: BQA2GEXO711FVBVXDWKM
      secret_access_key: uvgz3LCwWM3e400cDkQIH/y1Y4xgU4iV91CwFSPC

"%dev":
  quarkus:
    hibernate-orm:
      database:
        generation: update
      sql-load-script: import-dev.sql
      log:
        sql: false
    flyway:
      migrate-at-start: false
