quarkus:
  resteasy:
    path: /api
  datasource:
    db-kind: postgresql
    jdbc:
      url: jdbc:postgresql://localhost:5432/xsender_db
    username: xsender_username
    password: xsender_password
  hibernate-orm:
    database:
      generation: update
  quartz:
    clustered: false
  artemis:
    url: tcp://localhost:61616
    username: quarkus
    password: quarkus
    health:
      enabled: false
  oidc:
    enabled: true
    auth-server-url: http://localhost:8180/auth/realms/openubl
    client-id: xsender
    credentials:
      secret: secret
  http:
    auth:
      permission:
        hmtl:
          paths: /*
          policy: permit
        api:
          paths: /api/*
          policy: authenticated
openubl:
  event-manager:
    type: basic
    basic:
      retry-delay: 43200000
    jms:
      delay: 500
      callbackQueue: callbackQueue
      sendFileQueue: sendFileQueue
      ticketQueue: ticketQueue
  storage:
    type: filesystem
    filesystem:
      folder: target/xsender-server-storage
    s3:
      host: http://localhost:9000
      region: us-east-1
      bucket: project-openubl
      access_key_id: BQA2GEXO711FVBVXDWKM
      secret_access_key: uvgz3LCwWM3e400cDkQIH/y1Y4xgU4iV91CwFSPC
