---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: ublhub-db
  labels:
    app.kubernetes.io/name: ublhub-db
    app.kubernetes.io/component: database
    app.kubernetes.io/instance: ublhub-db
    app.kubernetes.io/part-of: openubl-ublhub
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi