---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ublhub.fullname" . }}-db
  labels:
    {{- include "ublhub.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.database.username | quote }}
  password: {{ .Values.database.password | quote }}
  database: {{ .Values.database.database | quote }}
