name: CI

on:
  push:
    branches-ignore:
      - "dependabot/**"
    paths-ignore:
      - "README.md"
  pull_request:
    paths-ignore:
      - "README.md"

jobs:
  backend-jvm-tests:
    name: Backend JVM Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: 11
          distribution: temurin
          cache: maven
      - name: Maven
        run: mvn test

  admin-console-tests:
    name: Admin Console Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 12.x, 14.x ]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2.5.0
        with:
          node-version: ${{ matrix.node-version }}
      - name: Build
        working-directory: admin-console/src/main/webapp
        run: |
          yarn install
          yarn build
      - name: Test
        working-directory: admin-console/src/main/webapp
        run: yarn test --coverage --watchAll=false
      - uses: codecov/codecov-action@v2.1.0
        with:
          flags: unitests
